function myWindow() {
    full_name = document.getElementById("full_name").value;
    city = document.getElementById("city").value;
    state = document.getElementById("state").value;
    zip_code = document.getElementById("zip_code").value;
    phone = document.getElementById("phone").value;
    email = document.getElementById("email").value;
    linkedin = document.getElementById("linkedin").value;
    portfolio = document.getElementById("portfolio").value;
    coding_skills = document.getElementById("coding_skills").value;
    writing_skills = document.getElementById("writing_skills").value;
    work_ethic = document.getElementById("work_ethic").value;
    web_tools = document.getElementById("web_tools").value;
    programs = document.getElementById("programs").value;
    education = document.getElementById("education").value;
    start_date = document.getElementById("start_date").value;
    end_date = document.getElementById("end_date").value;
    employment = document.getElementById("employment").value;
    start_date2 = document.getElementById("start_date2").value;
    end_date2 = document.getElementById("end_date2").value;
    employment2 = document.getElementById("employment2").value;
    start_date3 = document.getElementById("start_date3").value;
    end_date3 = document.getElementById("end_date3").value;
    employment3 = document.getElementById("employment3").value;
    business_references = document.getElementById("business_references").value;
    myResume = ("<html>\n<head>\n<title>Your Resume</title>\n</head>\n<body style=font-family:arial;>");
    myResume += ("<div class=full_name style=color:white;background:black;font-size:60px;>" + full_name + "</div>\n</br>");
    myResume += (city + ", " + state + " " + zip_code + " &#9670; " + phone + " &#9670; " + email + "</br>");
    myResume += (linkedin + " &#9670; " + portfolio + "</br></br>");
    myResume += ("<div class=heading style=color:gray;font-size:45px;border-bottom:solid;border-bottom-color:rebeccapurple;>Web Developer</div>");
    myResume += ("<div class=coding_writing_work style=padding-left:0px;>\n<ul>\n<li>" + coding_skills + "</li>\n</br>\n<li>" + writing_skills + "</li>\n</br>\n<li>" + work_ethic + "</li>\n</ul>\n</div>\n</br>");
    myResume += ("<div class=heading2 style=color:gray;font-size:45px;border-bottom:solid;border-bottom-color:rebeccapurple;>Technical Toolbox</div>\n</br>");
    myResume += ("<b>Web Tools:</b>\n<div class=web_tools style=float:right;padding-left:30px;width:85%;>" + web_tools + "</div>\n</br>\n</br>\n</br>");
    myResume += ("<b>Programs:</b>\n<div class=programs style=float:right;padding-left:30px;width:85%;>" + programs + "</div>\n</br>\n</br>\n</br>");
    myResume += ("<div class=heading3 style=color:gray;font-size:45px;border-bottom:solid;border-bottom-color:rebeccapurple;>Education</div>\n</br>");
    myResume += ("<div class=education style=white-space:pre-wrap;padding-left:10px;>" + education + "</div>\n</br>\n</br>");
    myResume += ("<div id=heading2 style=color:gray;font-size:45px;border-bottom:solid;border-bottom-color:rebeccapurple;>Web Development Experience</div>\n</br>");
    myResume += ("<div class=start_end_date style=padding-left:10px;>\n<b>" + start_date + " - " + end_date + "</b>\n</div>\n</br>");
    myResume += ("<div class=employment style=white-space:pre-wrap;padding-left:10px;>" + employment + "</div>\n</br>\n</br>");
    myResume += ("<div class=start_end_date2 style=padding-left:10px;>\n<b>" + start_date2 + " - " + end_date2 + "</b>\n</div>\n</br>");
    myResume += ("<div class=employment2 style=white-space:pre-wrap;padding-left:10px;>" + employment2 + "</div>\n</br>\n</br>");
    myResume += ("<div class=start_end_date3 style=padding-left:10px;>\n<b>" + start_date3 + " - " + end_date3 + "</b>\n</div>\n</br>");
    myResume += ("<div class=employment3 style=white-space:pre-wrap;padding-left:10px;>" + employment3 + "</div>\n</br>\n</br>");
    myResume += ("<div id=heading4 style=color:gray;font-size:45px;border-bottom:solid;border-bottom-color:rebeccapurple;>Business References</div>\n</br>");
    myResume += ("<div class=business_references style=white-space:pre-wrap;padding-left:10px;>" + business_references + "</div>");
    myResume += ("</body>\n</html>");
    flyWindow = window.open('about:blank', 'myPopUpResume', 'width=900, height=900, left=200, top=50');
    flyWindow.document.write(myResume);
};
document.getElementById("resume_builder").addEventListener("submit", myWindow);